---
title: "Day 2"
author: "Lukas Gröninger"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme:
      bootswatch: minty
      code_font: !expr bslib::font_google("Fira Code")
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```



```{r}
library(tidyverse)
library(here)


```

# Part 1

```{r}
input <- readLines(here("data", "Day2_input_1.txt"), warn = FALSE) 

df <- tibble(input = input) |> 
  separate(input, into = c("dir", "value"), sep = " ") |> 
  mutate(value = as.numeric(value),
         value = if_else(dir == "up", -1*value, value))

horizontal <- df |> 
  filter(dir == "forward") |> 
  summarize(sum(value)) |> 
  pull()

vertical <- df |> 
  filter(dir != "forward") |> 
  summarize(sum(value)) |> 
  pull()

result <- horizontal * vertical
```


# Part 2


```{r}
# The horizontal position does not change?


aim_function <- function(x) {
  
}

forward <- df |> 
  filter(dir == "forward") |> 
  pull()

aim <- 0

for (i in 1:nrow(df)) {

  while (df$dir[i] != "forward") {
    aim <- aim + df$value[i]
    i <- i + 1
    
  }
  
  for (j in 1:length(forward)) {
    
  }
  depth <- aim * 
}




aim <- 0
depth <- 0
  
for (i in 1:nrow(df)) {
  
  while (df$dir[i] != "forward") {
    aim <- aim + df$value[i]
    i <- i + 1
  }
  depth <- depth + df$value[i] * aim
  
}

depth * horizontal

directions <- tribble(
  ~dir, ~ x, ~ y,
  "down", 0, 1,
  "up", 0, -1,
  "forward", 1, 0
)


joined <- tibble(input = input) |> 
  separate(input, into = c("dir", "value"), sep = " ") |> 
  inner_join(directions) |> 
  mutate(value = as.numeric(value),
         aim = cumsum(y * value)) |> 
  summarize(horizontal = sum(value * x),
            depth = sum(aim * value * x),
            product = horizontal * depth)



```










